# Generated by Django 5.2.17 on 2026-09-30 02:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe un proyecto con ese nombre.'}, max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('pais', models.CharField(blank=True, max_length=80)),
                ('latitud', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitud', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('moneda', models.CharField(choices=[('CLP', 'Peso chileno'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='CLP', max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-activo', 'nombre'],
            },
        ),
    ]
