# Generated by Django 5.2.17 on 2026-09-30 02:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('desde', models.DateField(default=django.utils.timezone.localdate)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='organizacion.empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'asignación',
                'verbose_name_plural': 'asignaciones',
                'ordering': ['-desde'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empleados',
            field=models.ManyToManyField(related_name='proyectos', through='proyectos.Asignacion', to='organizacion.empleado'),
        ),
    ]
