# Generated by Django 5.2.17 on 2026-09-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('empleado', 'Empleado')], default='empleado', max_length=20),
        ),
    ]
