# Generated by Django 5.2.17 on 2026-09-30 01:25

import apps.nucleo.campos
import apps.nucleo.validadores
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe un departamento con ese nombre.'}, max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_inicio', models.DateField(validators=[apps.nucleo.validadores.NoFutura('La fecha de inicio no puede ser futura.')])),
                ('direccion', apps.nucleo.campos.CampoCifrado(blank=True)),
                ('telefono', apps.nucleo.campos.CampoCifrado(blank=True, validators=[apps.nucleo.validadores.telefono_chileno])),
                ('salario', apps.nucleo.campos.CampoCifrado(tipo=int, validators=[django.core.validators.MinValueValidator(1, 'El salario debe ser mayor que cero.')])),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='organizacion.departamento')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_a_cargo', to='organizacion.empleado'),
        ),
    ]
