# Generated by Django 5.2.17 on 2026-10-01 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('proyectos', '0002_asignaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('descripcion', models.TextField(blank=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='organizacion.empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'registro de tiempo',
                'verbose_name_plural': 'registros de tiempo',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
