# Generated by Django 5.2.17 on 2026-10-01 00:27

import apps.nucleo.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_registro_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotiempo',
            name='fecha',
            field=models.DateField(validators=[apps.nucleo.validadores.NoFutura('No se pueden registrar horas en fechas futuras.')]),
        ),
        migrations.AlterField(
            model_name='registrotiempo',
            name='horas',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[apps.nucleo.validadores.media_hora]),
        ),
    ]
